#!/bin/sh
export PATH=$PATH:/usr/sbin

echo "Updating pages for project #$1"

cd /htdocs/cache

wget -Oindex_$1.new "http://localhost/pc_index.php?project_id=$1"
chmod 644 index_$1.new
chown nugget:www index_$1.new
mv index_$1.inc index_$1.bak
mv index_$1.new index_$1.inc

wget -Ocountries_o_$1.new "http://localhost/misc/pc_countries.php?project_id=$1\&source=o"
chmod 644 countries_o_$1.new
chown nugget:www countries_o_$1.new
mv countries_o_$1.inc countries_o_$1.bak
mv countries_o_$1.new countries_o_$1.inc

wget -Ocountries_y_$1.new "http://localhost/misc/pc_countries.php?project_id=$1\&source=y"
chmod 644 countries_y_$1.new
chown nugget:www countries_y_$1.new
mv countries_y_$1.inc countries_y_$1.bak
mv countries_y_$1.new countries_y_$1.inc

if [ $1 != 3 -a $1 != 5 ]; then
    wget -Omoney_$1.new "http://localhost/misc/pc_money.php?project_id=$1"
    chmod 644 money_$1.new
    chown nugget:www money_$1.new
    mv money_$1.inc money_$1.bak
    mv money_$1.new money_$1.inc
fi
